import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="bg-gray-100 text-gray-900">
        <div className="min-h-screen flex flex-col">
          <header className="bg-white shadow px-6 py-4 flex justify-between">
            <h1 className="font-bold text-lg text-black">Task Manager</h1>
            <nav className="space-x-4">
              <a href="/tasks" className="text-black hover:underline">
                Tasks
              </a>
              <a href="/login" className="text-black hover:underline">
                Login
              </a>
            </nav>
          </header>

          <main className="flex-1 p-6 max-w-3xl mx-auto w-full text-black font-bold">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}